### ISSUE TITLE
Logging data to wandb with same key

### ISSUE THREAD

**Issue by ayulockin** [deep-diver/TFX-WandB#2]
In the `training_pipeline/modules/ViT.py` file, line [64-66](https://github.com/deep-diver/TFX-WandB/blob/25a96b0e517e9d9f4d430d94a31f44ac09de43ff/training_pipeline/modules/ViT.py#L64) are logging data to wandb with the same key `"optimizer"`.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/31141479/224299019-8411a6f6-a0a9-4f65-8513-dc79abef955f.png">

**Comment by deep-diver** [comment]
Thanks. I thought I fixed this, but it looks like I forgot 😅

**Comment by ayulockin** [comment]
let me make a quick PR
